### MessagesController

### POST - Send Message
POST https://224kb3ec07.execute-api.sa-east-1.amazonaws.com/Prod/api/messages/send
Content-Type: application/json

{
  "MessageId": "a1b2c3d4-e5f6-7890-1234-567890abcdef",
  "ConversationId": "conversa-da-turma-do-trabalho",
  "SenderId": "joao-super-chato",
  "RecipientId": "bia-a-melhor",
  "Content": "E aee, vamo tomar uma depois do trampo? 😎",
  "SentAt": "2025-09-08T18:30:00Z",
  "Status": "enviada",
  "Version": 1,
  "IdempotencyKey": "tentando-nao-dar-erro-de-novo",
  "DeliveryAttempts": 1
}


### POST - Delivered Message
POST https://224kb3ec07.execute-api.sa-east-1.amazonaws.com/Prod/api/messages/123/delivered
Content-Type: application/json


### POST - Read Message
POST https://224kb3ec07.execute-api.sa-east-1.amazonaws.com/Prod/api/messages/123/read
Content-Type: application/json


### GET - List Messages
GET https://224kb3ec07.execute-api.sa-east-1.amazonaws.com/Prod/api/messages/list


### GET - List values
GET https://224kb3ec07.execute-api.sa-east-1.amazonaws.com/Prod/api/values


### POST - Create Message
POST https://224kb3ec07.execute-api.sa-east-1.amazonaws.com/Prod/api/messages/create
Content-Type: application/json

{
  "message": "Hello World"
}